# Generated by Django 4.2.4 on 2023-08-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('S', 'Sightseeing'), ('T', 'Things To-Do'), ('F', 'Food')], default='S', max_length=1)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('travelItinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.travelitinerary')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
