# Generated by Django 4.2.4 on 2023-08-22 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelitinerary',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelitinerary',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
