# Generated by Django 4.2.4 on 2023-08-23 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_activity_name_activity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelitinerary',
            name='hotel',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
